version: '2'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    user: "1883"
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    env_file:
      - ./services/mariadb/mariadb.env
    volumes:
      - ./volumes/mariadb/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - backend

  mmrtls-rest:
    build: ../rest
    image: mmrtls-ctrlsrv-rest
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - backend
  
  mmrtls-app:
    build: ../app
    image: mmrtls-ctrlsrv-app
    ports:
      - 8000:8000
      - 15000:15000
    networks:
      - backend
    command: npm start

  mmrtls-processor:
    build: ../processor
    image: mmrtls-ctrlsrv-processor
    depends_on:
      - mariadb
      - mosquitto
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 9080:8080

networks:
    backend:
